# Generated by Django 6.0.1 on 2026-02-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationstatushistory',
            old_name='previous_status',
            new_name='old_status',
        ),
    ]
