# Generated by Django 6.0.1 on 2026-02-01 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(blank=True, max_length=100)),
                ('format_type', models.CharField(choices=[('standard', 'Standard Template'), ('latex', 'LaTeX Custom'), ('upload', 'Uploaded File')], default='standard', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('latex_source', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='resumes/uploads/')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='resumes/generated/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('experience', 'Work Experience'), ('education', 'Education'), ('skills', 'Skills'), ('certifications', 'Certifications'), ('projects', 'Projects')], max_length=30)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
