# Generated by Django 6.0.1 on 2026-02-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/'),
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resumes',
        ),
    ]
